FROM node as builder
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm cache clear --force
RUN npm ci
COPY . .
RUN npm run build
#ENTRYPOINT ["tail", "-f", "/dev/null"]


FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY pipeline/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]
